MyProjectsManager/MyProjectsManager.Web/Controllers/AspNetUsersController.cs
using System.Data.Entity;
using System.Threading.Tasks;
using System.Web.Mvc;
using MyProjectsManager.Data.Repositories;
using MyProjectsManager.Web.Attributes;

namespace MyProjectsManager.Web.Controllers
{
    [Authorize]
    [LayoutSupport]
    public class AspNetUsersController : BaseController
    {
        public override IAspNetUsersRepository AspNetUsersRepository { get; set; }
        public override ITeamsRepository TeamsRepository { get; set; }

        public AspNetUsersController(IAspNetUsersRepository aspNetUsersRepository, ITeamsRepository teamsRepository)
        {
            AspNetUsersRepository = aspNetUsersRepository;
            TeamsRepository = teamsRepository;
        }
        // GET: AspNetUsers
        public async Task<ActionResult> Index()
        {
            return View(await AspNetUsersRepository.GetBy(x=>x.Id!=CurrentUser.Id).ToListAsync());
        }
        

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                AspNetUsersRepository.Dispose();
                TeamsRepository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyProjectsManager/MyProjectsManager.Web/Controllers/TeamsController.cs
using System;
using System.Data.Entity;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using MyProjectsManager.Data;
using MyProjectsManager.Data.Repositories;
using MyProjectsManager.Web.Attributes;

namespace MyProjectsManager.Web.Controllers
{
    [Authorize]
    [LayoutSupport]
    public class TeamsController : BaseController
    {
        public override IAspNetUsersRepository AspNetUsersRepository { get; set; }
        public override ITeamsRepository TeamsRepository { get; set; }

        public TeamsController(IAspNetUsersRepository aspNetUsersRepository, ITeamsRepository teamsRepository)
        {
            AspNetUsersRepository = aspNetUsersRepository;
            TeamsRepository = teamsRepository;
        }
        // GET: Teams
        public async Task<ActionResult> Index()
        {
            return View(await TeamsRepository.GetAll().ToListAsync());
        }

        // GET: Teams/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Team team = await TeamsRepository.GetBy(x=>x.Id==id).FirstOrDefaultAsync();
            if (team == null)
            {
                return HttpNotFound();
            }
            return View(team);
        }

        // GET: Teams/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Teams/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,DateCreate,DateModified,OwnUserId,ProjectId")] Team team)
        {
            team.Id = Guid.NewGuid().ToString();
            team.DateCreate = DateTime.Now;
            if (!ModelState.IsValid) return View(team);
            TeamsRepository.Add(team);
            TeamsRepository.Save();
            return RedirectToAction("Index");
        }

        // GET: Teams/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Team team = await TeamsRepository.GetBy(x=>x.Id==id).FirstOrDefaultAsync();
            if (team == null)
            {
                return HttpNotFound();
            }
            return View(team);
        }

        // POST: Teams/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Title,DateCreate,DateModified,OwnUserId,ProjectId")] Team team)
        {
            if (!ModelState.IsValid) return View(team);
            var dbTeam = await TeamsRepository.GetBy(x => x.Id == team.Id).FirstOrDefaultAsync();
            if (dbTeam == null) return View(team);
            dbTeam.DateModified=DateTime.Now;
            UpdateModel(dbTeam);
            TeamsRepository.Save();
            return RedirectToAction("Index");
        }

        // GET: Teams/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Team team = await TeamsRepository.GetBy(x=>x.Id==id).FirstOrDefaultAsync();
            if (team == null)
            {
                return HttpNotFound();
            }
            return View(team);
        }

        // POST: Teams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            Team team = await TeamsRepository.GetBy(x=>x.Id==id).FirstOrDefaultAsync();
            TeamsRepository.Remove(team);
            TeamsRepository.Save();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                TeamsRepository.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

MyProjectsManager/MyProjectsManager.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My Projects Manager</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MY PROJECTS MANAGER", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Projects", "Index", "Projects")</li>
                    <li>@Html.ActionLink("Users", "Index", "AspNetUsers")</li>
                    @*<li>@Html.ActionLink("Tasks", "Index", "Tasks")</li>*@
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="" aria-expanded="false">
                            Teams <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Index","Teams")">Teams</a></li>
                            <li><a href="#" onclick="alert('Sorry! This function now not worked')">Import</a></li>
                            <li class="divider"></li>
                            <li><a href="#" onclick="alert('Sorry! This function now not worked')">Remove all teams</a></li>
                        </ul>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My Projects Manager</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>